[WIP] DT Experiments
LinkedEarth/paleoPandas pull request #6
Opened 2022-11-28 17:06 UTC by anirrudh

This PR Includes a notebook alongside a working environment. The notebook provides a quick way to look at the current implementation of non-nanosecond date times within pandas. 

The `environment.yaml` should work to go and fetch the last hash from the pandas package as defined. 

This PR will need a rebase, followed by some squashes, but I've opened this PR for visibility, and it will not be ready to merge as long as it is marked WIP.

2022-11-28 17:45 UTC, MarcoGorelli commented
> pandas powered by NumPy

this is typically the case :) Perhaps "Out-of-bounds datetimes going via numpy" would be a better title?

I'm fairly confident that it'll be the same thing later, when this can happen directly within `to_datetime` or `read_csv`, it'll just be hidden to users

2022-11-28 19:37 UTC, kcpevey requested changes

2022-11-28 19:37 UTC, kcpevey commented on ENVIRONMENT.md
> +# Environment Setup
I'd like to see these changes added to the README

2022-11-28 19:37 UTC, kcpevey commented on examples/L0_loading_to_series.ipynb
> +    "collapsed": false,
the untouched notebooks don't need to be added here.

2022-11-28 19:37 UTC, kcpevey commented on experiments/paleoclimdt/logic.py
> +import pathlib
this file is not necessary

2022-11-28 19:37 UTC, kcpevey commented on experiments/time_exploration_pandas.ipynb
> +{
This file can be added as a notebook in the examples folder that already exists. Please be sure to restart clear all

2022-12-02 19:46 UTC, anirrudh commented
Closing due to redundancies.

2022-12-02 19:46 UTC, closed without merging